# Generated by Django 5.1.7 on 2025-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playlist_song_cover_image_alter_song_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
